package com.examples.java;

public class JavaExceptionExample {

	public void testMethod() {
		System.out.println("Inside the test method");
	}

	public static void main(String[] args) {

		System.out.println("Program starts");

		/*int data = 100 / 0;

		System.out.println("Exception example 111");

*/		try {

	String name = null;
	name.equals("abc");
	int data = 100/0;
			JavaExceptionExample obj = new JavaExceptionExample();
			obj.testMethod();

			System.out.println("Exception example");

		} catch (Exception e) {
			System.out.println("Inside catch " + e);
		}

		System.out.println("After try catch ");
	}

}
